Repository emilsonfilho/SparseMatrix, pull requests merged in 2025-01, with the labels that each got.

#3 desempenho(format_all): codigo para formatar todo o codigo
  FormatAll.sh
Labels: documentation

#1 Func/implementacao classe node #004
  .gitignore
  .vscode/settings.json
  Includes/Classes/Node/Node.hpp
  Makefile
  Src/Classes/Node/Node.cpp
  tantofaz.cpp
Labels: enhancement

#4 Func/implementacao construtor iterator #008
  Includes/Classes/Iterator/Iterator.hpp
  Includes/Classes/Node/Node.hpp
  Makefile
  Src/Classes/Iterator/Iterator.cpp
  Src/Classes/Node/Node.cpp
Labels: bug, enhancement

#2 Func/adaptacao command design pattern #010
  .vscode/settings.json
  Defs/CommandInfo.hpp
  Defs/UnorderedMapCommand.hpp
  Includes/CommandPattern/Commands/Command.hpp
  Includes/CommandPattern/Commands/HelpCommand.hpp
  Includes/CommandPattern/Contexts/ContextCommand.hpp
  Includes/CommandPattern/Invoker/InvokerCommand.hpp
  Main.cpp
  Makefile
  Src/CommandPattern/Commands/HelpCommand.cpp
  Src/CommandPattern/Invoker/InvokerCommand.cpp
Labels: enhancement

#5 func(Iterator): adicionando movimentacao para o proximo elemento na l…
  Includes/Classes/Iterator/Iterator.hpp
  Src/Classes/Iterator/Iterator.cpp
Labels: enhancement

#7 func(Iterator): adicionando sobrecarga de operador
  Includes/Classes/Iterator/Iterator.hpp
  Src/Classes/Iterator/Iterator.cpp
Labels: enhancement

#13 refatoracao(Exceptions|Messages|Validation): adaptacao
  Exceptions/InvalidColumnException.hpp
  Exceptions/InvalidRowException.hpp
  Execeptions/exceptions.hpp
  Includes/Utils/Validation/Validation.hpp
  Message/mensagens.hpp
  Messages/Messages.hpp
  Src/Utils/Validation/Validation.cpp
  Validation/validation.hpp
Labels: bug, help wanted

#14 Hotfix: Refatoracao/command exceptions
  Includes/Classes/Iterator/Iterator.hpp
  Includes/CommandPattern/Invoker/InvokerCommand.hpp
  Includes/Exceptions/InvalidColumnException.hpp
  Includes/Exceptions/InvalidCommandException.hpp
  Includes/Exceptions/InvalidRowException.hpp
  Includes/Messages/Messages.hpp
  Includes/Utils/Validation/Validation.hpp
  Main.cpp
  Makefile
  Messages/Messages.hpp
  Src/CommandPattern/Invoker/InvokerCommand.cpp
  Src/Exceptions/InvalidColumnException.cpp
  Src/Exceptions/InvalidCommandException.cpp
  Src/Exceptions/InvalidRowException.cpp
  Src/Messages/Messages.cpp
  Src/Utils/Validation/Validation.cpp
Labels: bug, enhancement, help wanted

#15 Func(Iterator): Movimentacao e sobrecarga
  Includes/Classes/Iterator/Iterator.hpp
  Src/Classes/Iterator/Iterator.cpp
Labels: enhancement

#20 Hotfix/concerto impressao
  Includes/Classes/SparseMatrix/SparseMatrix.hpp
  Includes/CommandPattern/Contexts/PrintMatrixContextCommand.hpp
  Includes/Utils/Operations/PrintMatrix.hpp
  Makefile
  Src/Classes/SparseMatrix/SparseMatrix.cpp
  Src/CommandPattern/Commands/PrintMatrixCommand.cpp
  Src/Utils/Operations/PrintMatrix.cpp
Labels: invalid

#21 Refatoracao/validacao indices #023
  Includes/Messages/Messages.hpp
  Includes/Utils/Validation/Validation.hpp
  Src/Messages/Messages.cpp
  Src/Utils/Validation/Validation.cpp
Labels: enhancement, help wanted

#22 Func/implementacao comando get completo #027
  Defs/IntValidatorArray.hpp
  Defs/MatrixPtrArrayRef.hpp
  Defs/UserQuestions.hpp
  Includes/Classes/SparseMatrix/SparseMatrix.hpp
  Includes/CommandPattern/Commands/GetCommand.hpp
  Includes/CommandPattern/Contexts/GetContextCommand.hpp
  Includes/CommandPattern/Contexts/PrintMatrixContextCommand.hpp
  Includes/Exceptions/NoMatricesException.hpp
  Includes/Messages/Messages.hpp
  Includes/Utils/Tools/GetValidNumber.hpp
  Includes/Utils/Validation/Validation.hpp
  Main.cpp
  Makefile
  Src/Classes/SparseMatrix/SparseMatrix.cpp
  Src/CommandPattern/Commands/GetCommand.cpp
  Src/CommandPattern/Contexts/GetContextCommand.cpp
  Src/CommandPattern/Contexts/PrintMatrixContextCommand.cpp
  Src/Exceptions/NoMatricesException.cpp
  Src/Messages/Messages.cpp
  Src/Utils/Tools/GetValidNumber.cpp
  Src/Utils/Validation/Validation.cpp
Labels: bug, documentation, enhancement, help wanted

#19 Func/destrutor sparse matrix #021
  Includes/Classes/SparseMatrix/SparseMatrix.hpp
  Includes/Messages/Messages.hpp
  Src/Classes/SparseMatrix/SparseMatrix.cpp
  Src/Utils/Validation/Validation.cpp
Labels: enhancement
